### ISSUE TITLE
Export support?

### ISSUE THREAD

**Issue by gordol** [chimpler/postgres-aws-s3#10]
Is anyone here interested in extending this to support exports to s3?

Those were [added back in February in Aurora 3.1.0/11.6](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.20180305.html#AuroraPostgreSQL.Updates.20180305.310
).

See here for details:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/postgresql-s3-export.html

The function ref is [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/postgresql-s3-export.html#postgresql-s3-export-functions): but it looks like this:

```
aws_s3.query_export_to_s3(
    query text,    
    s3_info aws_commons._s3_uri_1,    
    options text
)
```

An example to dump JSON to S3 in JSONL format:
```
create extension aws_s3 cascade;

select * from aws_s3.query_export_to_s3(
    'select row_to_json(test) from (YOUR QUERY GOES HERE) test',
    aws_commons.create_s3_uri(
        'example-bucket/some/path',
        'somedata.jsonl',
        'us-east-1'),
    options :='format text');
```

**Comment by darthbear** [comment]
Thank you @gordol for the suggestion! I'll work on it when I have some free time!

**Comment by darthbear** [comment]
I tested it with the query:
```
select * from aws_s3.query_export_to_s3(
    'select row_to_json(test) from (select * from animals) test',
    aws_commons.create_s3_uri(
        'test-bucket',
        'somedata.json',
        'us-east-1'),
    options :='format text');
```

Seems to work fine. Thanks for the suggestion!

**Comment by gordol** [comment]
nice 🎉
